dropbox/goebpf

- goebpf_mock/mock_map.go
- loader.go
- map.go
- program_base.go
- program_xdp.go
- utils.go
- utils_test.go
It doesn't really make sense to depend on non-standard library to handle errors.
Getting rid of `godropbox/errors` by replacing with standard `errors` / `fmt` packages.
> [go errors] Remove unneeded dependency on godropbox/errors

- examples/xdp/packet_counter/.gitignore
- examples/xdp/packet_counter/Makefile
- examples/xdp/packet_counter/ebpf_prog/xdp.c
- examples/xdp/packet_counter/main.go
Adding very simple XDP / go program to count packets on interface grouped by L4 protocol.
Example could be built by simple `make`:
```bash
$ make
clang -I../../.. -O2 -target bpf -c ebpf_prog/xdp.c  -o ebpf_prog/xdp.elf
go build -v -o packet_counter
```
Requires `sudo` to run:
```bash
$ sudo ./packet_counter -iface=enp0s3
Maps:
protocols: Per-CPU array, Fd 5
Programs:
packet_count: XDP, size 29, license "GPLv2"
XDP program successfully loaded and attached. Counters refreshed every second.
PROTO_ICMP: 2 IPPROTO_TCP: 44 IPPROTO_UDP: 5
^C
Detaching program and exit
```
> Add XDP simple packet counter example

- ebpf.go
- goebpf_mock/mock_map.go
- goebpf_mock/mock_map_test.go
- itest/map_test.go
- map.go
A method to insert entries into a map regardless if the entry already existed or not was needed, so looking at sql, the term Upsert was chosen for the name to add this new method.
> Added Upsert method to map types, which will update an existing entry or insert one if the entry does not exist yet.

- itest/ebpf_prog/xdp1.c
- itest/xdp_test.go
- loader.go
Since order is not guaranteed it could cause something like
```
panic: runtime error: slice bounds out of range [recovered]
panic: runtime error: slice bounds out of range
goroutine 19 [running]:
testing.tRunner.func1(0xc42008e1e0)
/usr/lib/go-1.10/src/testing/testing.go:742 +0x29d
panic(0x7ffe40, 0xc8bd40)
/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
github.com/dropbox/goebpf.loadPrograms(0xc4200dadc0, 0xc420091740, 0x0, 0x0, 0x0)
/home/belyalov/go/src/github.com/dropbox/goebpf/loader.go:370 +0xfef
github.com/dropbox/goebpf.(*ebpfSystem).LoadElf(0xc42008cd20, 0x87b77c, 0x12, 0x0, 0x0)
/home/belyalov/go/src/github.com/dropbox/goebpf/loader.go:394 +0x152
```
This PR is also slightly refactors `xdp` integration test.
> [loader] Fix possible "slice bounds out of range" when one multiple programs in one ELF section

- bpf_helpers.h
- examples/xdp/xdp_dump/main.go
- perf_events.go
Also few minor fixes:
- Refactor `xdpdump` example: use goroutine to process perf events
- Add mock version of `bpf_perf_event_output()` - for cross compilation.
> [perf events] Close updates channel on Stop()

- itest/xdp_test.go
- program_xdp.go
I was originally confused by these constants:
```c
/* These are stored into IFLA_XDP_ATTACHED on dump. */
enum {
XDP_ATTACHED_NONE = 0,
XDP_ATTACHED_DRV,
XDP_ATTACHED_SKB,
XDP_ATTACHED_HW,
};
```
But correct constants are:
```c
#define XDP_FLAGS_UPDATE_IF_NOEXIST	(1U << 0)
#define XDP_FLAGS_SKB_MODE		(1U << 1)
#define XDP_FLAGS_DRV_MODE		(1U << 2)
#define XDP_FLAGS_HW_MODE		(1U << 3)
```
So fixed and itest added.
> [xdp/attach] Fix mode constants.

- map.go
- perf_events_handler.go
- program_base.go
- utils.go
Otherwise installing package under Mac produces some noise:
```bash
go/src/github.com/dropbox/goebpf/map.go:33:12: warning: 'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a supported interface. For SYS_kdebug_trace use kdebug_signpost(). [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:742:6: note: 'syscall' has been explicitly marked deprecated here
go/src/github.com/dropbox/goebpf/map.go:48:12: warning: 'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a supported interface. For SYS_kdebug_trace use kdebug_signpost(). [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:742:6: …
```
> [Mac] Gate all syscall() calls by C define to get rid of warnings

- ebpf.go
- goebpf_mock/mock_ebpf.go
- loader.go
This allows for embedding a compiled artifact directly into an ebpf program via something like [go-bindata](https://github.com/go-bindata/go-bindata) and wrapping a retrieved asset in something like a `bytes.Reader`.
> Add io.ReaderAt-based Load method

- bpf_helpers.h
- ebpf.go
- goebpf_mock/mock_map.go
- goebpf_mock/mock_map_test.go
- itest/map_test.go
- map.go
this implements the bpf_map_get_next_key for the library. 
- added the required interfaces and prototypes in bpf_helpers.h,
- created the cgo function and the go method (GetNextKey) for type EbpfMap to use the cgo function
- added tests under itest/map_test.go
edit: 
test results
```
=== RUN   TestMapSuite
=== RUN   TestMapSuite/TestArrayOfMaps
=== RUN   TestMapSuite/TestGetNextKey <<
=== RUN   TestMapSuite/TestHashOfMaps
=== RUN   TestMapSuite/TestMapArrayInt
=== RUN   TestMapSuite/TestMapArrayInt16
=== RUN   TestMapSuite/TestMapArrayUInt64
=== RUN   TestMapSuite/TestMapDoubleClose
=== RUN   TestMapSuite/TestMapFromExistingByFd
=== RUN   TestMapSuite/TestMapHash
=== RUN   TestMapSuite/TestMapLPMTrieIPv4
=== RUN   TestMapSuite/TestMapLPMTrieIPv6
=== RUN   TestMapSuite/TestMapPersistent …
```
> implement bpf_map_get_next_key

- bpf_helpers.h
this removes get_next_key function from kernel code (bpf_helpers.h), as this functionality is supposed to be used only in userland code. 
```
src/goebpf/itest# make test
././itest_test -test.v
=== RUN   TestKprobeSuite
=== RUN   TestKprobeSuite/TestElfLoad
=== RUN   TestKprobeSuite/TestKprobeEvents
--- PASS: TestKprobeSuite (0.51s)
--- PASS: TestKprobeSuite/TestElfLoad (0.29s)
--- PASS: TestKprobeSuite/TestKprobeEvents (0.23s)
=== RUN   TestMapSuite
=== RUN   TestMapSuite/TestArrayOfMaps
=== RUN   TestMapSuite/TestGetNextKeyInt
=== RUN   TestMapSuite/TestGetNextKeyString
=== RUN   TestMapSuite/TestHashOfMaps
=== RUN   TestMapSuite/TestMapArrayInt
=== RUN   TestMapSuite/TestMapArrayInt16
=== RUN   TestMapSuite/TestMapArrayUInt64
=== RUN   TestMapSuite/TestMapDoubleClose
=== RUN …
```
> removing get_next_key function from kernel-side code

- README.md
- bpf_helpers.h
- itest/Makefile
- itest/ebpf_prog/tc1.c
- itest/tc_test.go
- loader.go
- program_tc.go
this PR adds support for loading TC programs (sched_cls and sched_act)
also added missing prototype for bpf_skb_store_bytes helper, as well as the return codes used by this program.
i decided not to add TC_ACT_* in here, as they can be imported from `include/uapi/linux/pkt_cls.h`, and the BPF_* ones can be used for the basic use cases. 
not sure about the Attach() and Detach() methods, though - i couldn't find a good way of doing that. any ideas would be very much welcome!
without these two methods, the programs can still be loaded and pinned to bpffs using this library, and attached to the desired classifier/action using iproute2 `tc` command, by referencing the pinned file.
submitting this as a draft as i'd like to get some input on how to implement the Attach() and Detach() functions. …
> [tc-bpf] add support for tc-bpf program types

- bpf_helpers.h
adding here some flag values that bpf helper functions take, namely bpf_skb* functions; along with prototypes for `bpf_l3_csum_replace` and `bpf_l4_csum_replace` helpers.
also added a new `offsetof` function that can be used for getting an offset from a struct member, useful if passing offsets to these helpers are needed. example:
```
// we'll always get a l2 skb, so hardcode ethernet header in the logic
#define TTL_OFFSET (sizeof(struct ethhdr) + offsetof(struct iphdr, ttl))
#define CSUM_OFFSET (sizeof(struct ethhdr) + offsetof(struct iphdr, check))
#define HOPLIMIT_OFFSET (sizeof(struct ethhdr) + offsetof(struct ipv6hdr, hop_limit))
// pass ttl and csum field offsets to the functions to get them updated
bpf_skb_store_bytes(skb, TTL_OFFSET, &ttl, sizeof(__u8), 0); …
```
> [bpf-helpers] update bpf_helpers.h with flag values for some bpf helpers

- .travis.yml
- README.md
Subj,
`netlink ` library is no longer compatible with `go1.10`.
Let's get rid of it `go1.10`
> deprecate go1.10

- README.md
- examples/tc/packet_counter/Makefile
- examples/tc/packet_counter/ebpf_prog/tc.c
- examples/tc/packet_counter/ebpf_prog/tc.h
- examples/tc/packet_counter/main.go
- program_tc.go
Finish support for attaching BPF_PROG_TYPE_SCHED_CLS programs to the clsact pseudo-qdisc [1] in program_tc.
Implement an example packet counter under `examples/tc/packet_counter`.
[1] https://lwn.net/Articles/671458/
Signed-Off-By: Dan Fuhry <fuhry@dropbox.com>
> Implement Attach/Detach for TcProgramTypeCls, add packet_counter example

- doc.go
- loader.go
- map.go
- perf_events.go
- program_kprobe.go
- program_xdp.go
Required to have checks start passing in #68.
Command run: `gofmt -s -l -w .`
Go version:
```
$ pacman -Q go
go 2:1.19-1
```
Signed-off-by: Dan Fuhry <fuhry@dropbox.com>
> Apply gofmt 1.19 against repository

- .travis.yml
Remove the unusable version string "tip" from the list of go versions
to test against in CI. Deprecate testing against Go 1.11, 1.12 and 1.15,
and test only against 1.16 and 1.18 going forward.
Signed-Off-By: Dan Fuhry <fuhry@dropbox.com>
> Update CI to use just go 1.16 and 1.18, remove broken tip

- goebpf_mock/mock_map.go
- goebpf_mock/wrapper/wrapper.go
Fixes compilation error that recently began to appear.
Signed-off-by: Dan Fuhry <fuhry@dropbox.com>
> goebpf_mock: use __attribute__((weak)) on maps_head defs

- loader.go
- map.go
It appears that at one time, the relocation section for `maps` listed
the offset of the string within `.rodata` in the relocation symbol's
`value` field. In an executable compiled with clang 14.0.6, the
relocation table's `value` property was zeroed, and the pointer to the
correct string was actually in the original struct.
Output of `objdump`/`readelf` demonstrating this behavior change will
be posted in a comment on this pull request.
This commit updates the map loader to track the pointer value. The map
parser uses the value from the relocation table entry if it's nonzero,
and otherwise uses the value directly from the struct definition in
the original `maps` section.
Signed-off-by: Dan Fuhry <fuhry@dropbox.com>
> Fix string lookups in the map loader

- itest/kprobe_test.go
When newer `go test` runs, it writes the executable to a temporary path (under `/tmp`) under the name `itest.test`. However, if the same test executable is compiled and executed from the project directory the executable name has an underscore.
This PR updates the itest to accept both.
Signed-off-by: Dan Fuhry <fuhry@dropbox.com>
> Fix test executable name in itest/kprobe_test.go

- goebpf_mock/mock_map.go
- goebpf_mock/wrapper/wrapper.go
- itest/kprobe_test.go
- itest/path.go
- itest/perf_events_test.go
- itest/tc_test.go
- itest/xdp_test.go
Better handle situations where the working directory is not as expected. This PR specifically covers two scenarios:
1. Building parts of goebpf that use cgo when the working directory does not match the location of the target. We resolve this by removing relative paths anywhere `bpf_helpers.h` is included, instead passing that path as an `-I` argument to the compiler. This is done through a `#cgo` directive in the source but allows this to be overridden through other means such as a larger build system's CFLAGS.
2. Running the itest from a working directory other than `itest`. The tests now search the working directory first (preserving prior behavior) but also check for the image using the absolute path of the executable.
> More robust path handling in tests

- goebpf_mock/mock_map.go
- goebpf_mock/mock_map_test.go
- itest/map_test.go
- map.go
- utils.go
build showing the issue in the tests:
https://app.travis-ci.com/github/dropbox/goebpf/jobs/575825851
if we use the uninitialized value as the first key, it ends up skipping one of the keys.
> [bpf_get_next_key] add support for fetching the first key in map
